-- Users + auth codes tables for login/auth.
-- UUIDs are generated by the application (no Postgres extensions required).

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_codes (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  auth_code text NOT NULL,
  auth_code_plain text,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true
);

-- One active code per email.
CREATE UNIQUE INDEX IF NOT EXISTS auth_codes_one_active_per_email
  ON auth_codes(email)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS auth_codes_email_idx ON auth_codes(email);

CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  asset text NOT NULL,
  method text NOT NULL,
  destination text NOT NULL,
  note text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS withdrawal_requests_user_created_idx
  ON withdrawal_requests(user_id, created_at DESC);
